apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deployment
  labels:
    app: website
spec:
  replicas: 5
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
      - name: site-container
        image: <YOUR_DOCKERHUB_USERNAME>/beginner-site:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
